services:
  pipeline:
    build: .
    env_file: .env
    command: python master.py

  ui:
    build: .
    env_file: .env
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
